package pl.booklist.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.util.Objects;


/**
 * Represent a book entity in the BookList application.
 * Stores basic information about a book such as title, author, and ownership status.
 * Mapped to the "book" table in the database.
 * @author Paweł Opala
 * @version 1.0
  */
@Entity
@Table(name = "book")
public class Book {

    /**
     * Unique identifier for the book. Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the book. Cannot be blank and must not exceed 50 characters.
     */
    @Column(name = "title", nullable = false)
    @NotBlank
    @Size(max = 50)
    private String title;

    /**
     * Author of the book, Cannot be blank and must not exceed 100 characters.
     */
    @Column(name = "author" , nullable = false)
    @NotBlank
    @Size(max = 100)
    private String author;

    /**
     * Indicates whether the book is owned by the user.
     */
    @Column(name = "owned")
    private boolean owned;

    /**
     * Constructs a new Book instance with the specified title, author, and ownership status.
     *
     * @param title the title of the book
     * @param author the author of the book
     * @param owned true if the book is owned, false otherwise
     */
    public Book(String title, String author, boolean owned) {
        this.title = title;
        this.author = author;
        this.owned = owned;
    }

    /**
     * Default constructor required by JPA.
     */
    public Book() {
    }

    /**
     * Returns the unique identifier of the book.
     *
     * @return the book ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the book.
     *
     * @param id the book ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the title of the book.
     *
     * @return the book title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title of the book.
     *
     * @param title the book title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Sets the author of the book.
     *
     * @param author the book author
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Returns whether the book is owned.
     *
     * @return true if owned, false otherwise
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * Sets the ownership status of the book.
     *
     * @param owned true if owned, false otherwise
     */
    public boolean isOwned() {
        return owned;
    }

    public void setOwned(boolean owned) {
        this.owned = owned;
    }

    /**
     * Compares this book to another object based on ID.
     *
     * @param o the object to compare
     * @return true if the IDs are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Book)) return false;
        Book book = (Book) o;
        return Objects.equals(id, book.id);
    }

    /**
     * Returns the hash code of the book based on its ID.
     *
     * @return the hash code
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }

    /**
     * Returns a string representation of the book.
     *
     * @return a string with book details
     */
    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                ", owned=" + owned +
                '}';
    }
}



