package pl.booklist.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.util.Objects;

/**
 * Represent a book entity in the BookList application.
 * Stores basic information about a book such as title, author, and ownership status.
 * Mapped to the "book" table in the database.
 * @author Paweł Opala
 * @version 1.0
  */
@Entity
@Table(name = "book")
public class Book {

    /**
     * Unique identifier for the book. Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Title of the book. Cannot be blank and must not exceed 50 characters.
     */
    @Column(name = "title", nullable = false)
    @NotBlank
    @Size(max = 50)
    private String title;

    /**
     * Author of the book, Cannot be blank and must not exceed 100 characters.
     */
    @Column(name = "author" , nullable = false)
    @NotBlank
    @Size(max = 100)
    private String author;

    /**
     * Indicates whether the book is owned by the user.
     */
    @Column(name = "owned")
    private boolean owned;

    /**
     * URL of the book's cover image, typically fetched from Google Books API.
     */
    @Column(name = "cover_url", length = 10000)
    private String coverUrl;

    /**
     * Constructs a new Book instance with the specified title, author, and ownership status.
     *
     * @param id the unique identifier of the book.
     * @param title  the title of the book
     * @param author the author of the book
     * @param owned  true if the book is owned, false otherwise
     */
    public Book(Long id, String title, String author, boolean owned, String coverUrl) {
        this.id = id;
        this.title = title;
        this.author = author;
        this.owned = owned;
        this.coverUrl = coverUrl;
    }

    /**
     * Default constructor required by JPA.
     */
    public Book() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getCoverUrl() {
        return coverUrl;
    }

    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    public boolean isOwned() {
        return owned;
    }

    public void setOwned(boolean owned) {
        this.owned = owned;
    }

    @Override
    public boolean equals(Object o) {
        if (o == null || getClass() != o.getClass()) return false;
        Book book = (Book) o;
        return owned == book.owned && Objects.equals(id, book.id) && Objects.equals(title, book.title) && Objects.equals(author, book.author) && Objects.equals(coverUrl, book.coverUrl);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, title, author, owned, coverUrl);
    }

    @Override
    public String toString() {
        return "Book{" +
                "id=" + id +
                ", title='" + title + '\'' +
                ", author='" + author + '\'' +
                ", owned=" + owned +
                ", coverUrl='" + coverUrl + '\'' +
                '}';
    }
}



